### ISSUE TITLE
Fix metrics config setup for source controller

### ISSUE THREAD

**Issue by aavarghese** [knative-sandbox/eventing-redis#70]
```
{"severity":"ERROR","timestamp":"2021-01-27T17:31:31.7621829Z","logger":"redis-stream-source","caller":"metrics/exporter.go:148","message":"Failed to get a valid metrics config","error":"metrics domain cannot be empty","logging.googleapis.com/labels":{},"logging.googleapis.com/sourceLocation":{"file":"knative.dev/pkg@v0.0.0-20210119162123-1bbf0a6436c3/metrics/exporter.go","line":"148","function":"knative.dev/pkg/metrics.UpdateExporter"},"stacktrace":"knative.dev/pkg/metrics.UpdateExporter\n\tknative.dev/pkg@v0.0.0-20210119162123-1bbf0a6436c3/metrics/exporter.go:148\nknative.dev/eventing/pkg/adapter/v2.MainWithInformers\n\tknative.dev/eventing@v0.20.1-0.20210120133253-5dc363dcb5be/pkg/adapter/v2/main.go:131\nknative.dev/eventing/pkg/adapter/v2.MainWithEnv\n\tknative.dev/eventing@v0.20.1-0.20210120133253-5dc363dcb5be/pkg/adapter/v2/main.go:105\nknative.dev/eventing/pkg/adapter/v2.MainWithContext\n\tknative.dev/eventing@v0.20.1-0.20210120133253-5dc363dcb5be/pkg/adapter/v2/main.go:80\nknative.dev/eventing/pkg/adapter/v2.Main\n\tknative.dev/eventing@v0.20.1-0.20210120133253-5dc363dcb5be/pkg/adapter/v2/main.go:76\nmain.main\n\tknative.dev/eventing-redis/source/cmd/receive_adapter/main.go:26\nruntime.main\n\truntime/proc.go:204"}
{"severity":"ERROR","timestamp":"2021-01-27T17:31:31.7622881Z","logger":"redis-stream-source","caller":"v2/main.go:132","message":"failed to create the metrics exporter{error 26 0  metrics domain cannot be empty}","logging.googleapis.com/labels":{},"logging.googleapis.com/sourceLocation":{"file":"knative.dev/eventing@v0.20.1-0.20210120133253-5dc363dcb5be/pkg/adapter/v2/main.go","line":"132","function":"knative.dev/eventing/pkg/adapter/v2.MainWithInformers"},"stacktrace":"knative.dev/eventing/pkg/adapter/v2.MainWithInformers\n\tknative.dev/eventing@v0.20.1-0.20210120133253-5dc363dcb5be/pkg/adapter/v2/main.go:132\nknative.dev/eventing/pkg/adapter/v2.MainWithEnv\n\tknative.dev/eventing@v0.20.1-0.20210120133253-5dc363dcb5be/pkg/adapter/v2/main.go:105\nknative.dev/eventing/pkg/adapter/v2.MainWithContext\n\tknative.dev/eventing@v0.20.1-0.20210120133253-5dc363dcb5be/pkg/adapter/v2/main.go:80\nknative.dev/eventing/pkg/adapter/v2.Main\n\tknative.dev/eventing@v0.20.1-0.20210120133253-5dc363dcb5be/pkg/adapter/v2/main.go:76\nmain.main\n\tknative.dev/eventing-redis/source/cmd/receive_adapter/main.go:26\nruntime.main\n\truntime/proc.go:204"}
```

Install source, and an instance of redis stream source. These error message appears in the logs.
Reference: https://github.com/knative-sandbox/eventing-redis/pull/68#discussion_r565332684

**Comment by mericano1** [comment]
I am having the same issue. Has anyone solved it ? Not sure if that is the reason the pod `redissource-mystream-1234` doesn't start. Here is the logs

```
{"severity":"ERROR","timestamp":"2022-02-05T18:04:07.811802Z","logger":"redis-stream-source","caller":"v2/main.go:132","message":"Failed to create the metrics exporter","error":"metrics domain cannot be empty","stacktrace":"knative.dev/eventing/pkg/adapter/v2.MainWithInformers\n\tknative.dev/eventing@v0.29.1-0.20220203104220-17487954d41a/pkg/adapter/v2/main.go:132\nknative.dev/eventing/pkg/adapter/v2.MainWithEnv\n\tknative.dev/eventing@v0.29.1-0.20220203104220-17487954d41a/pkg/adapter/v2/main.go:105\nknative.dev/eventing/pkg/adapter/v2.MainWithContext\n\tknative.dev/eventing@v0.29.1-0.20220203104220-17487954d41a/pkg/adapter/v2/main.go:80\nknative.dev/eventing/pkg/adapter/v2.Main\n\tknative.dev/eventing@v0.29.1-0.20220203104220-17487954d41a/pkg/adapter/v2/main.go:76\nmain.main\n\tknative.dev/eventing-redis/source/cmd/receive_adapter/main.go:26\nruntime.main\n\truntime/proc.go:225"}
{"severity":"WARNING","timestamp":"2022-02-05T18:04:07.8118593Z","logger":"redis-stream-source","caller":"v2/config.go:185","message":"Tracing configuration is invalid, using the no-op default{error 26 0  empty json tracing config}"}
{"severity":"WARNING","timestamp":"2022-02-05T18:04:07.8119215Z","logger":"redis-stream-source","caller":"v2/config.go:178","message":"Sink timeout configuration is invalid, default to -1 (no timeout)"}
panic: nil

goroutine 1 [running]:
knative.dev/eventing-redis/source/pkg/adapter.(*Adapter).newPool.func1(0xc0007104e0, 0xc00003c058, 0x43, 0xc0007860a0)
	knative.dev/eventing-redis/source/pkg/adapter/adapter.go:244 +0x466
knative.dev/eventing-redis/source/pkg/adapter.(*Adapter).Start(0xc0007104e0, 0x1e16eb8, 0xc000521e60, 0x0, 0x0)
	knative.dev/eventing-redis/source/pkg/adapter/adapter.go:76 +0x93
knative.dev/eventing/pkg/adapter/v2.MainWithInformers(0x1e16eb8, 0xc000521e60, 0x1be1e8e, 0x13, 0x1e2c140, 0xc000738900, 0x1c93fe0)
	knative.dev/eventing@v0.29.1-0.20220203104220-17487954d41a/pkg/adapter/v2/main.go:204 +0x1007
knative.dev/eventing/pkg/adapter/v2.MainWithEnv(0x1e177e8, 0xc0007141f0, 0x1be1e8e, 0x13, 0x1e2c140, 0xc000738900, 0x1c93fe0)
	knative.dev/eventing@v0.29.1-0.20220203104220-17487954d41a/pkg/adapter/v2/main.go:105 +0x22d
knative.dev/eventing/pkg/adapter/v2.MainWithContext(0x1e177e8, 0xc0007141f0, 0x1be1e8e, 0x13, 0x1c93fe8, 0x1c93fe0)
	knative.dev/eventing@v0.29.1-0.20220203104220-17487954d41a/pkg/adapter/v2/main.go:80 +0x75
knative.dev/eventing/pkg/adapter/v2.Main(0x1be1e8e, 0x13, 0x1c93fe8, 0x1c93fe0)
	knative.dev/eventing@v0.29.1-0.20220203104220-17487954d41a/pkg/adapter/v2/main.go:76 +0x98
main.main()
	knative.dev/eventing-redis/source/cmd/receive_adapter/main.go:26 +0x4e
```
